### ISSUE TITLE
Fix issues

### ISSUE THREAD

**Issue by FoksVHox** [JustPlayerDE/libgmodstore#6]
After the newest update to the addon page; 
![image](https://user-images.githubusercontent.com/37844753/84439813-36292180-ac39-11ea-9920-ac13bd456cde.png)

You're not able to enable any addons where the character count is bigger than 50

**Comment by justinkluever** [comment]
Fixed in MERGE-33
should be deployed in ~5 minutes

**Comment by justinkluever** [comment]
Note: the name limit where there before the update, i just forgot to increase it since you cannot directly change the addon name anymore
